if(EXISTS "/home/runner/work/powerflow/powerflow/build-sanitizers/PowerFlowUnitTests-b12d07c_tests.cmake")
  include("/home/runner/work/powerflow/powerflow/build-sanitizers/PowerFlowUnitTests-b12d07c_tests.cmake")
else()
  add_test(PowerFlowUnitTests_NOT_BUILT-b12d07c PowerFlowUnitTests_NOT_BUILT-b12d07c)
endif()
